baseURL = "https://vertcoin.org/"
DefaultContentLanguage = "en"
title = "Vertcoin"
theme = "elate"


#This file prints out code blocks



#Language


    [languages]
    [languages.en]
    languageName = "English"
    weight = 1

    [languages.fr]
    languageName = "Franc"
    weight = 2




#Parameters


[params]




  [params.navigation]


    [[params.navigation.item]]
     url = "download"
    [[params.navigation.item]]
    url = "purchase"
    [[params.navigation.item]]
    url = "team"
    [[params.navigation.item]]
    url = "donate"


  [params.action]

    [[params.navigationAction.item]]


  [params.desktopDownload]


    [[params.desktopButton.item]]




  [params.mobileDownload]

    [[params.mobileButton.item]]




  [params.intro]

      [[params.intro.item]]
        url = "mine"
        img = "start-mining.jpg"


      [[params.intro.item]]
        url = "buy-vertcoin"
        img = "buy-vertcoin.jpg"

      [[params.intro.item]]
        url = "accept-vertcoin"
        img = "accept-vertcoin.jpg"


      [[params.intro.item]]
        url = "community"
        img = "community.jpg"


# How Questions

    [params.howQuestion]
    [[params.howQuestion.item]]
    url = "specifications-explained"
    [[params.howQuestion.item]]
    url = "https://medium.com/vertcoin-blog/2017-in-review-2018-roadmap-d4ba51b29da3"


# Adoption Links

     [params.adoption]
        [[params.adoption.item]]
        url = "accept-vertcoin"
        [[params.adoption.item]]
        url = "buy-vertcoin"



# Guides

    [params.guide]
    [[params.guide.item]]
    url = "lightning"
    [[params.guide.item]]
    url = "specifications-explained"


# Social Links - Community Section



    [params.communityStatus]
    [[params.communityStatus.item]]
    social = [
            ["icon-reddit", "https://twitter.com/jamesl22"],
            ["icon-twitter", "https://github.com/metalicjames/"],
            ["icon-discord", "https://github.com/metalicjames/"]
          ]



 # About Section

  [params.about]


    [[params.about.item]]
      name = "James Lovejoy"
      img = "james.jpg"
      alt = "James Lovejoy"
      social = [
        ["icon-twitter", "https://twitter.com/jamesl22"],
        ["icon-github", "https://github.com/metalicjames/"]
      ]

    [[params.about.item]]
      name = "Joe Straub"
      img = "joe.jpg"
      alt = "Zemrys"
      social = [
        ["icon-github", "https://github.com/zemrys"]
      ]

    [[params.about.item]]
      name = "Eric Kubik"
      img = "eric.png"
      alt = "Eric"
      social = [
        ["icon-twitter", "https://twitter.com/etang600"]
      ]

    [[params.about.item]]
      name = "Star Im"
      img = "star.jpg"
      alt = "Star"
      social = []

    [[params.about.item]]
      name = "Bryan Goodson"
      img = "bryan.jpg"
      alt = "Bryan Goodson"
      social = [
        ["icon-twitter", "https://twitter.com/BryanGoodson"],
        ["icon-github", "https://github.com/Bryangoodson"],
        ["icon-linkedin", "https://www.linkedin.com/in/bgoodson"]
      ]

    [[params.about.item]]
      name = "Gert-Jaap Glasbergen"
      img = "gertjaap.jpg"
      alt = "Gert-Jaap Glasbergen"
      social = [
        ["icon-twitter", "https://twitter.com/gertjaap"],
        ["icon-github", "https://github.com/gertjaap"],
        ["icon-linkedin", "https://www.linkedin.com/in/gertjaap"]
      ]

    [[params.about.item]]
      name = "Alex Turek"
      img = "alex.jpg"
      alt = "Alex Turek"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/turekaj/"]
      ]

    [[params.about.item]]
      name = "jk_14"
      img = "person1.jpg"
      alt = "jk_14"
      social = []

    [[params.about.item]]
      name = "pknight"
      img = "person2.jpg"
      alt = "pknight"
      social = []

    [[params.about.item]]
      name = "Adam Rivera"
      img = "adam.jpg"
      alt = "a432511"
      social = [
        ["icon-twitter", "https://twitter.com/a432511"],
        ["icon-linkedin", "https://www.linkedin.com/in/adammrivera/"]
      ]

    [[params.about.item]]
      name = "Daiki"
      img = "daiki.jpg"
      alt = "Daiki"
      social = []

    [[params.about.item]]
      name = "Vertcoin Community"
      img = "placeholder.png"
      alt = "Community"
      social = []




 [params.contact]




  [params.footer]
    enable = true
    copyright = ''


